# language: node_js
# node_js:
#   - lts/*
# script:
#   - npm run build
# deploy:
#   provider: pages
#   skip-cleanup: true
#   local_dir: .vuepress/dist
#   github-token: $GITHUB_TOKEN
#   target-branch: gh-pages
#   keep-history: true
#   edge: true
#   on:
#     branch: master